---
- name: exercise 2
  hosts: All
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        update_cache: yes
        state: present
    - name: java installation
      ansible.builtin.apt:
        name: 
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    
        
